### PR TITLE
remote for-loop in decode

### PR DESCRIPTION
**Pull request by fanatid**
Should have some better performance, but probable less readable.
Feel free to drop this.

### CODE REVIEW

**Comment by dcousens** [comment]
s/remote/remove,  but sure :+1:

**Comment by dcousens** [comment]
If you replace `.length` with `4`,  I think the interpreter should make the same optimization?

**Comment by fanatid** [comment]
yea, of course remove, but it's uneasy for change :(
<s>I think number instead .length property not give any performance improvement</s>

Benchmark:
```js
'use strict'

var benchmark = require('benchmark')

var checksum = new Buffer([0x00, 0x40, 0x80, 0xb0])
var newChecksum = new Buffer(checksum)

new benchmark.Suite()
  .on('cycle', function (event) {
    console.log(String(event.target))
  })
  .on('complete', function () {
    console.log('--------------------------------------------------')
    console.log('Fastest is ' + this.filter('fastest').pluck('name'))
    console.log('==================================================')
  })
  .add('for', function () {
    for (var i = 0; i < newChecksum.length; ++i) {
      if (newChecksum[i] === checksum[i]) continue
      throw new Error('Invalid checksum')
    }
  })
  .add('for without .length', function () {
    for (var i = 0; i < 4; ++i) {
      if (newChecksum[i] === checksum[i]) continue
      throw new Error('Invalid checksum')
    }
  })
  .add('single if', function () {
    if (checksum[0] !== newChecksum[0] ||
        checksum[1] !== newChecksum[1] ||
        checksum[2] !== newChecksum[2] ||
        checksum[3] !== newChecksum[3]) {
      throw new Error('Invalid checksum')
    }
  })
  .run()
```

with result:
```
for x 25,545,194 ops/sec ±0.78% (98 runs sampled)
for without .length x 26,249,756 ops/sec ±0.17% (103 runs sampled)
single if x 26,955,176 ops/sec ±0.83% (93 runs sampled)
```

+2.5% + 2.5%, 5% is not too much, should we close this without merge? Is `if` more readable than for-loop?

**Comment by dcousens** [comment]
I actually think it is *as* readable, which, given the slight performance increase (consistently 5% here),  why not.

**Pull request merged**
