### PR TITLE
type definitions were added

### PR DESCRIPTION
**Pull request by muturgan**

### CODE REVIEW

**Comment by dnovacik** [comment]
this would be neat to have

**Comment by clemsos** [comment]
yep @junderw can this be merged plz?

**Comment by junderw** [comment]
Closed in favor of https://www.npmjs.com/package/@types/bs58check

**Comment by junderw** [comment]
An alternative PR I would accept:

1. Switch from Travis to Github Actions
2. Rewrite to TypeScript, commit the built directory (similar to how bitcoinjs-lib commits the src directory with the built files)
3. Rewrite/Run tests in TypeScript to prove the correctness of the types

tbh, the 3 steps above are a more trouble than the benefit they gain (not having to install @types/bs58check), the types repo is already tested and being maintained.

If someone is willing to do the above work, I'll review, merge, and publish... but I don't think it's worth it.

**Comment by clemsos** [comment]
Yes, make sense. I didn't find out about the types package at first. Seems like the best option indeed. Thank you !

**Comment by muturgan** [comment]
Correct me if I'm wrong.
But in my opinion switching from Travis to Github Actions is a work for a single PR.
And typescript staff is a work for another PR.

**Pull request closed without merging**
