### PR TITLE
Switch from create-hash to noble-hashes

### PR DESCRIPTION
**Pull request by paulmillr**

### CODE REVIEW

**Comment by junderw** [comment]
We should switch to UInt8Array by bumping bs58 to v5 (which uses it) and bs58check should also be bumped major version.

**Comment by paulmillr** [comment]
Done.

**Comment by junderw** [comment]
Replace lint with standard (what was there before)

Then I'll merge this and push a major version bump.

**Review by junderw — APPROVED** [review]

**Comment by junderw** [comment]
Published as v3.0.1

**Pull request merged**
