### PR TITLE
Optional checksum function

### PR DESCRIPTION
**Pull request by fanatid**
Issue #13 
@dcousens how this looks for you?

### CODE REVIEW

**Comment by dcousens** [comment]
Not bad.  But I wonder if we can do better.

Maybe the construction

``` js
function (checksum) {
   function encode (buffer) {
      ... checksum(buffer) ...
   }

   function decode (str) {
       ... checksum (buffer) ...
   }

  reutrn { encode, decode }
}
```

That way we don't have run-time parameterization,  and the default export is exactly the same.

**Comment by fanatid** [comment]
@dcousens changed.

**Comment by fanatid** [comment]
@dcousens ping :)

**Comment by dcousens** [comment]
whatever, I'll do that :+1:

**Comment by dcousens** [comment]
Released as `2.1.0` with https://github.com/bitcoinjs/bs58check/commit/b7f26dddd355e2a54be079887939a6fc8527c7f2 added

**Comment by fanatid** [comment]
Thank you.

**Pull request merged**
