### PR TITLE
crypto-hashing instead create-hash

### PR DESCRIPTION
**Pull request by fanatid**
+update bs58 dep

### CODE REVIEW

**Comment by dcousens** [comment]
`"crypto-hashing"` what a terrible name.
Honestly, this doesn't help readability at all.

**Comment by fanatid** [comment]
crypto-hash?

**Comment by dcousens** [comment]
Honestly,  I think the way it is now, is fine.
If you really want the modularized approach,  then `sha256x2` as a module.

But even that then means I have to go find out what underlying hash implementation is being used just to verify the code.

**Comment by fanatid** [comment]
I think crypto-hasing (or other name) is better than sha256x2, sha256ripemd160 because it contains all in one place, moreover allows use all hashes from createHash.
It means that you can remove whole file [bitcoinjs-lib/crypto.js](https://github.com/bitcoinjs/bitcoinjs-lib/blob/0cedacddc62718adaf22d3c5c094e51e149d0259/src/crypto.js) in v3.0.0

**Comment by dcousens** [comment]
@fanatid but does that abstraction make sense to make in the first place?
As an abstraction?

**Comment by fanatid** [comment]
sorry, don't understand, *in first place?*

**Comment by dcousens** [comment]
@fanatid does the abstraction make sense to use at all?

**Comment by fanatid** [comment]
Why not? With abstraction hash calculation:
```js
var output = cryptoHashing('sha256', input)
```
without:
```js
var output = createHash('sha256').update(input).digest()
```

**Comment by dcousens** [comment]
Exactly.
The latter makes it clear what is occurring,  the first means I have to find out what `cryptoHashing` actually does, what dependencies it uses. 
Etc.

Its just not worth the abstraction IMHO.

**Comment by fanatid** [comment]
@dcousens it's ridiculous, what about `cryptoHash` or all dependencies for hashes in `crypto-browserify`? Should you check what they do?
cryptocoinjs/bitcoinjs has so many modules, if you add one nothing changed, especially module with function that used in many other modules

**Comment by dcousens** [comment]
What else uses `sha256x2`?

**Comment by fanatid** [comment]
you mean who else except bitcoin/other cryptocurrencies uses sha256x2?

**Comment by dcousens** [comment]
`bs58check`, `bitcoinjs-lib`...
That's basically it right?

**Comment by dcousens** [comment]
@fanatid and not just `sha256x2`,  but specifically `hash256`, as its known.  And `hash160`, etc.

**Comment by fanatid** [comment]
> `bs58check`, `bitcoinjs-lib`...
That's basically it right?

yes, but you can find other: https://github.com/search?l=javascript&q=sha256x2&type=Code&utf8=%E2%9C%93

**Comment by fanatid** [comment]
I agree that name `crypto-hashing` is not best, but I like use 1shot instead update().digest()

**Comment by dcousens** [comment]
@fanatid I'd hazard most of them could just be using `bs58check` in the first place,  let alone the custom `sha256x2` module we might make now.

**Pull request closed without merging**
